### PR TITLE
Add AMD GPU scheduling support

### PR DESCRIPTION
**Pull request by dongahn**
This PR is the backport of AMD GPU support for the old scheduler. The PR for the graph based schedule is posted at https://github.com/flux-framework/flux-sched/pull/464.

### CODE REVIEW

**Comment by dongahn** [comment]
Add @grondo and @SteVwonder as the reviewers. 

@grondo: do we want to add execution support for AMD GPU binding support as well for corona and other AMD GPU based systems? 

The issue was created against the new execution system at https://github.com/flux-framework/flux-core/issues/2149. But if we will use our stable releases for CORONA or other AMD GPU based systems, I am wondering if we need to add support for https://github.com/flux-framework/flux-core/issues/2149 as well.

**Comment by dongahn** [comment]
Travis turned green and this is ready to be reviewed.

**Comment by grondo** [comment]
> This LGTM in terms of detecting AMD GPUs. @dongahn/@grondo, do we make support for VISIBLE_DEVICES (flux-framework/flux-core#2149) a separate PR?

Good question, do you think we should just have `cuda_devices.lua` also export `ROCR_VISIBLE_DEVICES`?

**Comment by dongahn** [comment]
> @dongahn/@grondo, do we make support for VISIBLE_DEVICES (flux-framework/flux-core#2149) a separate PR?

This has to be a separate PR since changes are needed in flux-core. 

> Good question, do you think we should just have cuda_devices.lua also export ROCR_VISIBLE_DEVICES?

@grondo: when/how is cuda_devices.lua activated? I'm wondering if we can make it such that rocm_devices.lua is activated when the system has AMD GPUs instead of NVIDIA GPUs. How do you currently detect whether the system has GPU? Do you get this from `R_lite`? Maybe `R_lite` can be extended to include device types...

**Comment by grondo** [comment]
> when/how is cuda_devices.lua activated?

The "plugin" is executed on every job. If a `gpu` member of `R_lite` is set, then `CUDA_VISIBLE_DEVICES` is set to the expanded form of the id set (also, `CUDA_DEVICE_ORDER` is set to `"PCI_BUS_ID"`, is there something similar to this for `ROCM`?)

> I'm wondering if we can make it such that rocm_devices.lua is activated when the system has AMD GPUs instead of NVIDIA GPUs.

Would there ever be a case where both AMD and other GPUs are on the same system?

In general, if a specific instance of a general type of resource is different enough to require a different binding strategy, we will need a way to differentiate the subtype of the resource during containment (I hadn't thought of that before). For v0.11 though, would it be sufficient to set *both* `{CUDA,ROCM}_VISIBLE_DEVICES`, since we don't want to spend excessive time on development of this branch?

**Comment by grondo** [comment]
> we will need a way to differentiate the subtype of the resource during containment (I hadn't thought of that before).

Does the resource system support an inheritance model for resource types (kind of like we had in RDL)? If the inheritance of resources could be encoded in *R* somehow, this could be a powerful method to extend handling of resource containment (or any other subsystem that might require implementation differences for slightly different resource types).

E.g. `ROCM` could inherit from `GPU` (which could inherit from `Device` or maybe even `Coproc`). This way users could ask for either generic `GPU` or more specific models of gpu by the subclass type. During containment, there could be different plugins for each type of GPU, but also more generic handlers for GPUs if necessary.

**Comment by dongahn** [comment]
> The "plugin" is executed on every job. If a gpu member of R_lite is set, then CUDA_VISIBLE_DEVICES is set to the expanded form of the id set (also, CUDA_DEVICE_ORDER is set to "PCI_BUS_ID", is there something similar to this for ROCM?)

I don't know the answer to that. My guess is probably. Let's ask around... maybe Edgar knows.

**Comment by dongahn** [comment]
> Would there ever be a case where both AMD and other GPUs are on the same system?

@trws' chimera machine has this configuration but this will be just very rare on real systems. At least for a foreseeable future.

**Comment by dongahn** [comment]
> In general, if a specific instance of a general type of resource is different enough to require a different binding strategy, we will need a way to differentiate the subtype of the resource during containment (I hadn't thought of that before). 

I think this is an important case. A trend is, nore and more accelerators are being introduced to HPC. For GPU, it used be only NVIDIA. But now we have AMD and Intel introducing their own for HPC. I don't expect one formula will work for all of these. 

> For v0.11 though, would it be sufficient to set both {CUDA,ROCM}_VISIBLE_DEVICES, since we don't want to spend excessive time on development of this branch?

This sounds reasonable to me. Maybe we use this plugin as is: not even setting ROCM one. @trws tells me that `CUDA_VISIBLE_DEVICES` is recognized for AMD GPU. So I don't know what's the effect of setting both at the same time. Maybe just better leave it as is and have `CUDA_VISIBLE_DEVICES` do the magic for AMD. Someone will have to test it on a real system though.

**Comment by dongahn** [comment]
> Does the resource system support an inheritance model for resource types (kind of like we had in RDL)? If the inheritance of resources could be encoded in R somehow, this could be a powerful method to extend handling of resource containment (or any other subsystem that might require implementation differences for slightly different resource types).

We don't have this but I would think that this is reasonable to add. Given the current resource model architecture, I would add such inheritance information into the `type` field of a resource vertex. 

> E.g. ROCM could inherit from GPU (which could inherit from Device or maybe even Coproc). This way users could ask for either generic GPU or more specific models of gpu by the subclass type. During containment, there could be different plugins for each type of GPU, but also more generic handlers for GPUs if necessary.

For example, the type field for AMD, NVIDIA, and Intel GPUs would be, respectively:

`type: device.gpu.amd_gpu`
`type: device.gpu.nvidia_gpu`
`type: device.gpu.intel_gpu`

During matching, the type field of the jobspec can be matched from the most derived type to least. 

We can also do this by putting more specific model information into the property field of a resource vertex as well. I would think this is probably what most schedulers use.

**Comment by dongahn** [comment]
For now though, it sounds like this PR can be merged then. Can @SteVwonder or @grondo push the button?

**Pull request merged**
